name: CI

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, synchronize]

jobs:
    build-test-lint:
        name: Build, test and lint
        timeout-minutes: 15
        runs-on: ubuntu-latest
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
            TURBO_REMOTE_ONLY: true

        steps:
            - name: Check out the repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: Set up a Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Test
              run: npm run test

            - name: Lint
              run: npm run lint
